@startuml
!include style.puml
skinparam ArrowFontStyle plain

box Model MODEL_COLOR_T1
participant ":Model" as Model MODEL_COLOR
participant ":VersionedTripLog" as VersionedTripLog MODEL_COLOR
end box

[-> Model : undoTripLog()
activate Model

Model -> VersionedTripLog : undo()
activate VersionedTripLog

VersionedTripLog -> VersionedTripLog :resetData(ReadOnlyTripLog)
VersionedTripLog --> Model :
deactivate VersionedTripLog

[<-- Model
deactivate Model

@enduml
